// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `ImuMonitor.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <ImuMonitor.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 304
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 2
#       error Ice patch level mismatch!
#   endif
#endif

static const ::std::string __ImuDataCommunication__ImuMonitor__updateImuData_name = "updateImuData";

static const ::std::string __ImuDataCommunication__RawImuMonitor__updateImuData_name = "updateImuData";

::Ice::Object* IceInternal::upCast(::ImuDataCommunication::ImuMonitor* p) { return p; }
::IceProxy::Ice::Object* IceInternal::upCast(::IceProxy::ImuDataCommunication::ImuMonitor* p) { return p; }

::Ice::Object* IceInternal::upCast(::ImuDataCommunication::RawImuMonitor* p) { return p; }
::IceProxy::Ice::Object* IceInternal::upCast(::IceProxy::ImuDataCommunication::RawImuMonitor* p) { return p; }

void
ImuDataCommunication::__read(::IceInternal::BasicStream* __is, ::ImuDataCommunication::ImuMonitorPrx& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::ImuDataCommunication::ImuMonitor;
        v->__copyFrom(proxy);
    }
}

void
ImuDataCommunication::__read(::IceInternal::BasicStream* __is, ::ImuDataCommunication::RawImuMonitorPrx& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::ImuDataCommunication::RawImuMonitor;
        v->__copyFrom(proxy);
    }
}

void
ImuDataCommunication::OpenMatImuData::__write(::IceInternal::BasicStream* __os) const
{
    __os->write(openMatId);
    __os->write(timestamp);
    __os->write(xAcc);
    __os->write(yAcc);
    __os->write(zAcc);
    __os->write(xGyro);
    __os->write(yGyro);
    __os->write(zGyro);
    __os->write(xMag);
    __os->write(yMag);
    __os->write(zMag);
    __os->write(wQuat);
    __os->write(xQuat);
    __os->write(yQuat);
    __os->write(zQuat);
    __os->write(xEuler);
    __os->write(yEuler);
    __os->write(zEuler);
    if(rotationM.size() == 0)
    {
        __os->writeSize(0);
    }
    else
    {
        __os->write(&rotationM[0], &rotationM[0] + rotationM.size());
    }
}

void
ImuDataCommunication::OpenMatImuData::__read(::IceInternal::BasicStream* __is)
{
    __is->read(openMatId);
    __is->read(timestamp);
    __is->read(xAcc);
    __is->read(yAcc);
    __is->read(zAcc);
    __is->read(xGyro);
    __is->read(yGyro);
    __is->read(zGyro);
    __is->read(xMag);
    __is->read(yMag);
    __is->read(zMag);
    __is->read(wQuat);
    __is->read(xQuat);
    __is->read(yQuat);
    __is->read(zQuat);
    __is->read(xEuler);
    __is->read(yEuler);
    __is->read(zEuler);
    __is->read(rotationM);
}

void
ImuDataCommunication::RawImuData::__write(::IceInternal::BasicStream* __os) const
{
    __os->write(timestamp);
    __os->write(xAcc);
    __os->write(yAcc);
    __os->write(zAcc);
    __os->write(xGyro);
    __os->write(yGyro);
    __os->write(zGyro);
    __os->write(xMag);
    __os->write(yMag);
    __os->write(zMag);
}

void
ImuDataCommunication::RawImuData::__read(::IceInternal::BasicStream* __is)
{
    __is->read(timestamp);
    __is->read(xAcc);
    __is->read(yAcc);
    __is->read(zAcc);
    __is->read(xGyro);
    __is->read(yGyro);
    __is->read(zGyro);
    __is->read(xMag);
    __is->read(yMag);
    __is->read(zMag);
}

void
IceProxy::ImuDataCommunication::ImuMonitor::updateImuData(const ::ImuDataCommunication::OpenMatImuData& id, const ::Ice::Context* __ctx)
{
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::ImuDataCommunication::ImuMonitor* __del = dynamic_cast< ::IceDelegate::ImuDataCommunication::ImuMonitor*>(__delBase.get());
            __del->updateImuData(id, __ctx);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::ImuDataCommunication::ImuMonitor::begin_updateImuData(const ::ImuDataCommunication::OpenMatImuData& id, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __ImuDataCommunication__ImuMonitor__updateImuData_name, __del, __cookie);
    try
    {
        __result->__prepare(__ImuDataCommunication__ImuMonitor__updateImuData_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__getOs();
        id.__write(__os);
        __os->endWriteEncaps();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::ImuDataCommunication::ImuMonitor::end_updateImuData(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __ImuDataCommunication__ImuMonitor__updateImuData_name);
}

const ::std::string&
IceProxy::ImuDataCommunication::ImuMonitor::ice_staticId()
{
    return ::ImuDataCommunication::ImuMonitor::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::ImuDataCommunication::ImuMonitor::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::ImuDataCommunication::ImuMonitor);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::ImuDataCommunication::ImuMonitor::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::ImuDataCommunication::ImuMonitor);
}

::IceProxy::Ice::Object*
IceProxy::ImuDataCommunication::ImuMonitor::__newInstance() const
{
    return new ImuMonitor;
}

void
IceProxy::ImuDataCommunication::RawImuMonitor::updateImuData(const ::ImuDataCommunication::RawImuData& id, const ::Ice::Context* __ctx)
{
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::ImuDataCommunication::RawImuMonitor* __del = dynamic_cast< ::IceDelegate::ImuDataCommunication::RawImuMonitor*>(__delBase.get());
            __del->updateImuData(id, __ctx);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::ImuDataCommunication::RawImuMonitor::begin_updateImuData(const ::ImuDataCommunication::RawImuData& id, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __ImuDataCommunication__RawImuMonitor__updateImuData_name, __del, __cookie);
    try
    {
        __result->__prepare(__ImuDataCommunication__RawImuMonitor__updateImuData_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__getOs();
        id.__write(__os);
        __os->endWriteEncaps();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::ImuDataCommunication::RawImuMonitor::end_updateImuData(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __ImuDataCommunication__RawImuMonitor__updateImuData_name);
}

const ::std::string&
IceProxy::ImuDataCommunication::RawImuMonitor::ice_staticId()
{
    return ::ImuDataCommunication::RawImuMonitor::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::ImuDataCommunication::RawImuMonitor::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::ImuDataCommunication::RawImuMonitor);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::ImuDataCommunication::RawImuMonitor::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::ImuDataCommunication::RawImuMonitor);
}

::IceProxy::Ice::Object*
IceProxy::ImuDataCommunication::RawImuMonitor::__newInstance() const
{
    return new RawImuMonitor;
}

void
IceDelegateM::ImuDataCommunication::ImuMonitor::updateImuData(const ::ImuDataCommunication::OpenMatImuData& id, const ::Ice::Context* __context)
{
    ::IceInternal::Outgoing __og(__handler.get(), __ImuDataCommunication__ImuMonitor__updateImuData_name, ::Ice::Normal, __context);
    try
    {
        ::IceInternal::BasicStream* __os = __og.os();
        id.__write(__os);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(!__og.is()->b.empty())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.is()->skipEmptyEncaps();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateM::ImuDataCommunication::RawImuMonitor::updateImuData(const ::ImuDataCommunication::RawImuData& id, const ::Ice::Context* __context)
{
    ::IceInternal::Outgoing __og(__handler.get(), __ImuDataCommunication__RawImuMonitor__updateImuData_name, ::Ice::Normal, __context);
    try
    {
        ::IceInternal::BasicStream* __os = __og.os();
        id.__write(__os);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(!__og.is()->b.empty())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.is()->skipEmptyEncaps();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateD::ImuDataCommunication::ImuMonitor::updateImuData(const ::ImuDataCommunication::OpenMatImuData& id, const ::Ice::Context* __context)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::ImuDataCommunication::OpenMatImuData& id, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_id(id)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::ImuDataCommunication::ImuMonitor* servant = dynamic_cast< ::ImuDataCommunication::ImuMonitor*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->updateImuData(_m_id, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::ImuDataCommunication::OpenMatImuData& _m_id;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __ImuDataCommunication__ImuMonitor__updateImuData_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(id, __current);
        try
        {
            __direct.servant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

void
IceDelegateD::ImuDataCommunication::RawImuMonitor::updateImuData(const ::ImuDataCommunication::RawImuData& id, const ::Ice::Context* __context)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::ImuDataCommunication::RawImuData& id, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_id(id)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::ImuDataCommunication::RawImuMonitor* servant = dynamic_cast< ::ImuDataCommunication::RawImuMonitor*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->updateImuData(_m_id, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::ImuDataCommunication::RawImuData& _m_id;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __ImuDataCommunication__RawImuMonitor__updateImuData_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(id, __current);
        try
        {
            __direct.servant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

::Ice::ObjectPtr
ImuDataCommunication::ImuMonitor::ice_clone() const
{
    throw ::Ice::CloneNotImplementedException(__FILE__, __LINE__);
    return 0; // to avoid a warning with some compilers
}

static const ::std::string __ImuDataCommunication__ImuMonitor_ids[2] =
{
    "::Ice::Object",
    "::ImuDataCommunication::ImuMonitor"
};

bool
ImuDataCommunication::ImuMonitor::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__ImuDataCommunication__ImuMonitor_ids, __ImuDataCommunication__ImuMonitor_ids + 2, _s);
}

::std::vector< ::std::string>
ImuDataCommunication::ImuMonitor::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__ImuDataCommunication__ImuMonitor_ids[0], &__ImuDataCommunication__ImuMonitor_ids[2]);
}

const ::std::string&
ImuDataCommunication::ImuMonitor::ice_id(const ::Ice::Current&) const
{
    return __ImuDataCommunication__ImuMonitor_ids[1];
}

const ::std::string&
ImuDataCommunication::ImuMonitor::ice_staticId()
{
    return __ImuDataCommunication__ImuMonitor_ids[1];
}

::Ice::DispatchStatus
ImuDataCommunication::ImuMonitor::___updateImuData(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.is();
    __is->startReadEncaps();
    ::ImuDataCommunication::OpenMatImuData id;
    id.__read(__is);
    __is->endReadEncaps();
    updateImuData(id, __current);
    return ::Ice::DispatchOK;
}

static ::std::string __ImuDataCommunication__ImuMonitor_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "updateImuData"
};

::Ice::DispatchStatus
ImuDataCommunication::ImuMonitor::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< ::std::string*, ::std::string*> r = ::std::equal_range(__ImuDataCommunication__ImuMonitor_all, __ImuDataCommunication__ImuMonitor_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __ImuDataCommunication__ImuMonitor_all)
    {
        case 0:
        {
            return ___ice_id(in, current);
        }
        case 1:
        {
            return ___ice_ids(in, current);
        }
        case 2:
        {
            return ___ice_isA(in, current);
        }
        case 3:
        {
            return ___ice_ping(in, current);
        }
        case 4:
        {
            return ___updateImuData(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
ImuDataCommunication::ImuMonitor::__write(::IceInternal::BasicStream* __os) const
{
    __os->writeTypeId(ice_staticId());
    __os->startWriteSlice();
    __os->endWriteSlice();
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
    Object::__write(__os);
#else
    ::Ice::Object::__write(__os);
#endif
}

void
ImuDataCommunication::ImuMonitor::__read(::IceInternal::BasicStream* __is, bool __rid)
{
    if(__rid)
    {
        ::std::string myId;
        __is->readTypeId(myId);
    }
    __is->startReadSlice();
    __is->endReadSlice();
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
    Object::__read(__is, true);
#else
    ::Ice::Object::__read(__is, true);
#endif
}

// COMPILERFIX: Stream API is not supported with VC++ 6
#if !defined(_MSC_VER) || (_MSC_VER >= 1300)
void
ImuDataCommunication::ImuMonitor::__write(const ::Ice::OutputStreamPtr&) const
{
    Ice::MarshalException ex(__FILE__, __LINE__);
    ex.reason = "type ImuDataCommunication::ImuMonitor was not generated with stream support";
    throw ex;
}

void
ImuDataCommunication::ImuMonitor::__read(const ::Ice::InputStreamPtr&, bool)
{
    Ice::MarshalException ex(__FILE__, __LINE__);
    ex.reason = "type ImuDataCommunication::ImuMonitor was not generated with stream support";
    throw ex;
}
#endif

void 
ImuDataCommunication::__patch__ImuMonitorPtr(void* __addr, ::Ice::ObjectPtr& v)
{
    ::ImuDataCommunication::ImuMonitorPtr* p = static_cast< ::ImuDataCommunication::ImuMonitorPtr*>(__addr);
    assert(p);
    *p = ::ImuDataCommunication::ImuMonitorPtr::dynamicCast(v);
    if(v && !*p)
    {
        IceInternal::Ex::throwUOE(::ImuDataCommunication::ImuMonitor::ice_staticId(), v->ice_id());
    }
}

::Ice::ObjectPtr
ImuDataCommunication::RawImuMonitor::ice_clone() const
{
    throw ::Ice::CloneNotImplementedException(__FILE__, __LINE__);
    return 0; // to avoid a warning with some compilers
}

static const ::std::string __ImuDataCommunication__RawImuMonitor_ids[2] =
{
    "::Ice::Object",
    "::ImuDataCommunication::RawImuMonitor"
};

bool
ImuDataCommunication::RawImuMonitor::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__ImuDataCommunication__RawImuMonitor_ids, __ImuDataCommunication__RawImuMonitor_ids + 2, _s);
}

::std::vector< ::std::string>
ImuDataCommunication::RawImuMonitor::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__ImuDataCommunication__RawImuMonitor_ids[0], &__ImuDataCommunication__RawImuMonitor_ids[2]);
}

const ::std::string&
ImuDataCommunication::RawImuMonitor::ice_id(const ::Ice::Current&) const
{
    return __ImuDataCommunication__RawImuMonitor_ids[1];
}

const ::std::string&
ImuDataCommunication::RawImuMonitor::ice_staticId()
{
    return __ImuDataCommunication__RawImuMonitor_ids[1];
}

::Ice::DispatchStatus
ImuDataCommunication::RawImuMonitor::___updateImuData(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.is();
    __is->startReadEncaps();
    ::ImuDataCommunication::RawImuData id;
    id.__read(__is);
    __is->endReadEncaps();
    updateImuData(id, __current);
    return ::Ice::DispatchOK;
}

static ::std::string __ImuDataCommunication__RawImuMonitor_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "updateImuData"
};

::Ice::DispatchStatus
ImuDataCommunication::RawImuMonitor::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< ::std::string*, ::std::string*> r = ::std::equal_range(__ImuDataCommunication__RawImuMonitor_all, __ImuDataCommunication__RawImuMonitor_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __ImuDataCommunication__RawImuMonitor_all)
    {
        case 0:
        {
            return ___ice_id(in, current);
        }
        case 1:
        {
            return ___ice_ids(in, current);
        }
        case 2:
        {
            return ___ice_isA(in, current);
        }
        case 3:
        {
            return ___ice_ping(in, current);
        }
        case 4:
        {
            return ___updateImuData(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
ImuDataCommunication::RawImuMonitor::__write(::IceInternal::BasicStream* __os) const
{
    __os->writeTypeId(ice_staticId());
    __os->startWriteSlice();
    __os->endWriteSlice();
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
    Object::__write(__os);
#else
    ::Ice::Object::__write(__os);
#endif
}

void
ImuDataCommunication::RawImuMonitor::__read(::IceInternal::BasicStream* __is, bool __rid)
{
    if(__rid)
    {
        ::std::string myId;
        __is->readTypeId(myId);
    }
    __is->startReadSlice();
    __is->endReadSlice();
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
    Object::__read(__is, true);
#else
    ::Ice::Object::__read(__is, true);
#endif
}

// COMPILERFIX: Stream API is not supported with VC++ 6
#if !defined(_MSC_VER) || (_MSC_VER >= 1300)
void
ImuDataCommunication::RawImuMonitor::__write(const ::Ice::OutputStreamPtr&) const
{
    Ice::MarshalException ex(__FILE__, __LINE__);
    ex.reason = "type ImuDataCommunication::RawImuMonitor was not generated with stream support";
    throw ex;
}

void
ImuDataCommunication::RawImuMonitor::__read(const ::Ice::InputStreamPtr&, bool)
{
    Ice::MarshalException ex(__FILE__, __LINE__);
    ex.reason = "type ImuDataCommunication::RawImuMonitor was not generated with stream support";
    throw ex;
}
#endif

void 
ImuDataCommunication::__patch__RawImuMonitorPtr(void* __addr, ::Ice::ObjectPtr& v)
{
    ::ImuDataCommunication::RawImuMonitorPtr* p = static_cast< ::ImuDataCommunication::RawImuMonitorPtr*>(__addr);
    assert(p);
    *p = ::ImuDataCommunication::RawImuMonitorPtr::dynamicCast(v);
    if(v && !*p)
    {
        IceInternal::Ex::throwUOE(::ImuDataCommunication::RawImuMonitor::ice_staticId(), v->ice_id());
    }
}
