// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `ImuMonitor.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <ImuMonitor.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __ImuDataCommunication__ImuMonitor__updateImuData_name = "updateImuData";

const ::std::string __ImuDataCommunication__RawImuMonitor__updateImuData_name = "updateImuData";

}

namespace Ice
{
}
::IceProxy::Ice::Object* ::IceProxy::ImuDataCommunication::upCast(::IceProxy::ImuDataCommunication::ImuMonitor* p) { return p; }

void
::IceProxy::ImuDataCommunication::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::ImuDataCommunication::ImuMonitor>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::ImuDataCommunication::ImuMonitor;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::ImuDataCommunication::ImuMonitor::updateImuData(const ::ImuDataCommunication::OpenMatImuData& id, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __ImuDataCommunication__ImuMonitor__updateImuData_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::ImuDataCommunication::ImuMonitor* __del = dynamic_cast< ::IceDelegate::ImuDataCommunication::ImuMonitor*>(__delBase.get());
            __del->updateImuData(id, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::ImuDataCommunication::ImuMonitor::begin_updateImuData(const ::ImuDataCommunication::OpenMatImuData& id, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __ImuDataCommunication__ImuMonitor__updateImuData_name, __del, __cookie);
    try
    {
        __result->__prepare(__ImuDataCommunication__ImuMonitor__updateImuData_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(id);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::ImuDataCommunication::ImuMonitor::end_updateImuData(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __ImuDataCommunication__ImuMonitor__updateImuData_name);
}

const ::std::string&
IceProxy::ImuDataCommunication::ImuMonitor::ice_staticId()
{
    return ::ImuDataCommunication::ImuMonitor::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::ImuDataCommunication::ImuMonitor::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::ImuDataCommunication::ImuMonitor);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::ImuDataCommunication::ImuMonitor::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::ImuDataCommunication::ImuMonitor);
}

::IceProxy::Ice::Object*
IceProxy::ImuDataCommunication::ImuMonitor::__newInstance() const
{
    return new ImuMonitor;
}
::IceProxy::Ice::Object* ::IceProxy::ImuDataCommunication::upCast(::IceProxy::ImuDataCommunication::RawImuMonitor* p) { return p; }

void
::IceProxy::ImuDataCommunication::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::ImuDataCommunication::RawImuMonitor>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::ImuDataCommunication::RawImuMonitor;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::ImuDataCommunication::RawImuMonitor::updateImuData(const ::ImuDataCommunication::RawImuData& id, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __ImuDataCommunication__RawImuMonitor__updateImuData_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::ImuDataCommunication::RawImuMonitor* __del = dynamic_cast< ::IceDelegate::ImuDataCommunication::RawImuMonitor*>(__delBase.get());
            __del->updateImuData(id, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::ImuDataCommunication::RawImuMonitor::begin_updateImuData(const ::ImuDataCommunication::RawImuData& id, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __ImuDataCommunication__RawImuMonitor__updateImuData_name, __del, __cookie);
    try
    {
        __result->__prepare(__ImuDataCommunication__RawImuMonitor__updateImuData_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(id);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::ImuDataCommunication::RawImuMonitor::end_updateImuData(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __ImuDataCommunication__RawImuMonitor__updateImuData_name);
}

const ::std::string&
IceProxy::ImuDataCommunication::RawImuMonitor::ice_staticId()
{
    return ::ImuDataCommunication::RawImuMonitor::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::ImuDataCommunication::RawImuMonitor::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::ImuDataCommunication::RawImuMonitor);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::ImuDataCommunication::RawImuMonitor::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::ImuDataCommunication::RawImuMonitor);
}

::IceProxy::Ice::Object*
IceProxy::ImuDataCommunication::RawImuMonitor::__newInstance() const
{
    return new RawImuMonitor;
}

void
IceDelegateM::ImuDataCommunication::ImuMonitor::updateImuData(const ::ImuDataCommunication::OpenMatImuData& id, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __ImuDataCommunication__ImuMonitor__updateImuData_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(id);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(__og.hasResponse())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.readEmptyParams();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateM::ImuDataCommunication::RawImuMonitor::updateImuData(const ::ImuDataCommunication::RawImuData& id, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __ImuDataCommunication__RawImuMonitor__updateImuData_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(id);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(__og.hasResponse())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.readEmptyParams();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateD::ImuDataCommunication::ImuMonitor::updateImuData(const ::ImuDataCommunication::OpenMatImuData& id, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::ImuDataCommunication::OpenMatImuData& __p_id, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_id(__p_id)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::ImuDataCommunication::ImuMonitor* servant = dynamic_cast< ::ImuDataCommunication::ImuMonitor*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->updateImuData(_m_id, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::ImuDataCommunication::OpenMatImuData& _m_id;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __ImuDataCommunication__ImuMonitor__updateImuData_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(id, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

void
IceDelegateD::ImuDataCommunication::RawImuMonitor::updateImuData(const ::ImuDataCommunication::RawImuData& id, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::ImuDataCommunication::RawImuData& __p_id, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_id(__p_id)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::ImuDataCommunication::RawImuMonitor* servant = dynamic_cast< ::ImuDataCommunication::RawImuMonitor*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->updateImuData(_m_id, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::ImuDataCommunication::RawImuData& _m_id;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __ImuDataCommunication__RawImuMonitor__updateImuData_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(id, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

::Ice::Object* ImuDataCommunication::upCast(::ImuDataCommunication::ImuMonitor* p) { return p; }

namespace
{
const ::std::string __ImuDataCommunication__ImuMonitor_ids[2] =
{
    "::Ice::Object",
    "::ImuDataCommunication::ImuMonitor"
};

}

bool
ImuDataCommunication::ImuMonitor::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__ImuDataCommunication__ImuMonitor_ids, __ImuDataCommunication__ImuMonitor_ids + 2, _s);
}

::std::vector< ::std::string>
ImuDataCommunication::ImuMonitor::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__ImuDataCommunication__ImuMonitor_ids[0], &__ImuDataCommunication__ImuMonitor_ids[2]);
}

const ::std::string&
ImuDataCommunication::ImuMonitor::ice_id(const ::Ice::Current&) const
{
    return __ImuDataCommunication__ImuMonitor_ids[1];
}

const ::std::string&
ImuDataCommunication::ImuMonitor::ice_staticId()
{
    return __ImuDataCommunication__ImuMonitor_ids[1];
}

::Ice::DispatchStatus
ImuDataCommunication::ImuMonitor::___updateImuData(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::ImuDataCommunication::OpenMatImuData id;
    __is->read(id);
    __inS.endReadParams();
    updateImuData(id, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __ImuDataCommunication__ImuMonitor_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "updateImuData"
};

}

::Ice::DispatchStatus
ImuDataCommunication::ImuMonitor::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__ImuDataCommunication__ImuMonitor_all, __ImuDataCommunication__ImuMonitor_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __ImuDataCommunication__ImuMonitor_all)
    {
        case 0:
        {
            return ___ice_id(in, current);
        }
        case 1:
        {
            return ___ice_ids(in, current);
        }
        case 2:
        {
            return ___ice_isA(in, current);
        }
        case 3:
        {
            return ___ice_ping(in, current);
        }
        case 4:
        {
            return ___updateImuData(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
ImuDataCommunication::ImuMonitor::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
ImuDataCommunication::ImuMonitor::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
ImuDataCommunication::__patch(ImuMonitorPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::ImuDataCommunication::ImuMonitorPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::ImuDataCommunication::ImuMonitor::ice_staticId(), v);
    }
}

::Ice::Object* ImuDataCommunication::upCast(::ImuDataCommunication::RawImuMonitor* p) { return p; }

namespace
{
const ::std::string __ImuDataCommunication__RawImuMonitor_ids[2] =
{
    "::Ice::Object",
    "::ImuDataCommunication::RawImuMonitor"
};

}

bool
ImuDataCommunication::RawImuMonitor::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__ImuDataCommunication__RawImuMonitor_ids, __ImuDataCommunication__RawImuMonitor_ids + 2, _s);
}

::std::vector< ::std::string>
ImuDataCommunication::RawImuMonitor::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__ImuDataCommunication__RawImuMonitor_ids[0], &__ImuDataCommunication__RawImuMonitor_ids[2]);
}

const ::std::string&
ImuDataCommunication::RawImuMonitor::ice_id(const ::Ice::Current&) const
{
    return __ImuDataCommunication__RawImuMonitor_ids[1];
}

const ::std::string&
ImuDataCommunication::RawImuMonitor::ice_staticId()
{
    return __ImuDataCommunication__RawImuMonitor_ids[1];
}

::Ice::DispatchStatus
ImuDataCommunication::RawImuMonitor::___updateImuData(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::ImuDataCommunication::RawImuData id;
    __is->read(id);
    __inS.endReadParams();
    updateImuData(id, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __ImuDataCommunication__RawImuMonitor_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "updateImuData"
};

}

::Ice::DispatchStatus
ImuDataCommunication::RawImuMonitor::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__ImuDataCommunication__RawImuMonitor_all, __ImuDataCommunication__RawImuMonitor_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __ImuDataCommunication__RawImuMonitor_all)
    {
        case 0:
        {
            return ___ice_id(in, current);
        }
        case 1:
        {
            return ___ice_ids(in, current);
        }
        case 2:
        {
            return ___ice_isA(in, current);
        }
        case 3:
        {
            return ___ice_ping(in, current);
        }
        case 4:
        {
            return ___updateImuData(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
ImuDataCommunication::RawImuMonitor::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
ImuDataCommunication::RawImuMonitor::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
ImuDataCommunication::__patch(RawImuMonitorPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::ImuDataCommunication::RawImuMonitorPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::ImuDataCommunication::RawImuMonitor::ice_staticId(), v);
    }
}
