// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `ImuMonitor.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __ImuMonitor_h__
#define __ImuMonitor_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace ImuDataCommunication
{

class ImuMonitor;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::ImuDataCommunication::ImuMonitor>&);
::IceProxy::Ice::Object* upCast(::IceProxy::ImuDataCommunication::ImuMonitor*);

class RawImuMonitor;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::ImuDataCommunication::RawImuMonitor>&);
::IceProxy::Ice::Object* upCast(::IceProxy::ImuDataCommunication::RawImuMonitor*);

}

}

namespace ImuDataCommunication
{

class ImuMonitor;
bool operator==(const ImuMonitor&, const ImuMonitor&);
bool operator<(const ImuMonitor&, const ImuMonitor&);
::Ice::Object* upCast(::ImuDataCommunication::ImuMonitor*);
typedef ::IceInternal::Handle< ::ImuDataCommunication::ImuMonitor> ImuMonitorPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::ImuDataCommunication::ImuMonitor> ImuMonitorPrx;
void __patch(ImuMonitorPtr&, const ::Ice::ObjectPtr&);

class RawImuMonitor;
bool operator==(const RawImuMonitor&, const RawImuMonitor&);
bool operator<(const RawImuMonitor&, const RawImuMonitor&);
::Ice::Object* upCast(::ImuDataCommunication::RawImuMonitor*);
typedef ::IceInternal::Handle< ::ImuDataCommunication::RawImuMonitor> RawImuMonitorPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::ImuDataCommunication::RawImuMonitor> RawImuMonitorPrx;
void __patch(RawImuMonitorPtr&, const ::Ice::ObjectPtr&);

}

namespace ImuDataCommunication
{

typedef ::std::vector< ::Ice::Float> MatrixSq;

struct OpenMatImuData
{
    ::Ice::Int openMatId;
    ::Ice::Float timestamp;
    ::Ice::Float xAcc;
    ::Ice::Float yAcc;
    ::Ice::Float zAcc;
    ::Ice::Float xGyro;
    ::Ice::Float yGyro;
    ::Ice::Float zGyro;
    ::Ice::Float xMag;
    ::Ice::Float yMag;
    ::Ice::Float zMag;
    ::Ice::Float wQuat;
    ::Ice::Float xQuat;
    ::Ice::Float yQuat;
    ::Ice::Float zQuat;
    ::Ice::Float xEuler;
    ::Ice::Float yEuler;
    ::Ice::Float zEuler;
    ::ImuDataCommunication::MatrixSq rotationM;
};

struct RawImuData
{
    ::Ice::Float timestamp;
    ::Ice::Float xAcc;
    ::Ice::Float yAcc;
    ::Ice::Float zAcc;
    ::Ice::Float xGyro;
    ::Ice::Float yGyro;
    ::Ice::Float zGyro;
    ::Ice::Float xMag;
    ::Ice::Float yMag;
    ::Ice::Float zMag;
};

}

namespace Ice
{
template<>
struct StreamableTraits< ::ImuDataCommunication::OpenMatImuData>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 73;
    static const bool fixedLength = false;
};

template<class S>
struct StreamWriter< ::ImuDataCommunication::OpenMatImuData, S>
{
    static void write(S* __os, const ::ImuDataCommunication::OpenMatImuData& v)
    {
        __os->write(v.openMatId);
        __os->write(v.timestamp);
        __os->write(v.xAcc);
        __os->write(v.yAcc);
        __os->write(v.zAcc);
        __os->write(v.xGyro);
        __os->write(v.yGyro);
        __os->write(v.zGyro);
        __os->write(v.xMag);
        __os->write(v.yMag);
        __os->write(v.zMag);
        __os->write(v.wQuat);
        __os->write(v.xQuat);
        __os->write(v.yQuat);
        __os->write(v.zQuat);
        __os->write(v.xEuler);
        __os->write(v.yEuler);
        __os->write(v.zEuler);
        __os->write(v.rotationM);
    }
};

template<class S>
struct StreamReader< ::ImuDataCommunication::OpenMatImuData, S>
{
    static void read(S* __is, ::ImuDataCommunication::OpenMatImuData& v)
    {
        __is->read(v.openMatId);
        __is->read(v.timestamp);
        __is->read(v.xAcc);
        __is->read(v.yAcc);
        __is->read(v.zAcc);
        __is->read(v.xGyro);
        __is->read(v.yGyro);
        __is->read(v.zGyro);
        __is->read(v.xMag);
        __is->read(v.yMag);
        __is->read(v.zMag);
        __is->read(v.wQuat);
        __is->read(v.xQuat);
        __is->read(v.yQuat);
        __is->read(v.zQuat);
        __is->read(v.xEuler);
        __is->read(v.yEuler);
        __is->read(v.zEuler);
        __is->read(v.rotationM);
    }
};

template<>
struct StreamableTraits< ::ImuDataCommunication::RawImuData>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 40;
    static const bool fixedLength = true;
};

template<class S>
struct StreamWriter< ::ImuDataCommunication::RawImuData, S>
{
    static void write(S* __os, const ::ImuDataCommunication::RawImuData& v)
    {
        __os->write(v.timestamp);
        __os->write(v.xAcc);
        __os->write(v.yAcc);
        __os->write(v.zAcc);
        __os->write(v.xGyro);
        __os->write(v.yGyro);
        __os->write(v.zGyro);
        __os->write(v.xMag);
        __os->write(v.yMag);
        __os->write(v.zMag);
    }
};

template<class S>
struct StreamReader< ::ImuDataCommunication::RawImuData, S>
{
    static void read(S* __is, ::ImuDataCommunication::RawImuData& v)
    {
        __is->read(v.timestamp);
        __is->read(v.xAcc);
        __is->read(v.yAcc);
        __is->read(v.zAcc);
        __is->read(v.xGyro);
        __is->read(v.yGyro);
        __is->read(v.zGyro);
        __is->read(v.xMag);
        __is->read(v.yMag);
        __is->read(v.zMag);
    }
};

}

namespace ImuDataCommunication
{

class Callback_ImuMonitor_updateImuData_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_ImuMonitor_updateImuData_Base> Callback_ImuMonitor_updateImuDataPtr;

class Callback_RawImuMonitor_updateImuData_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_RawImuMonitor_updateImuData_Base> Callback_RawImuMonitor_updateImuDataPtr;

}

namespace IceProxy
{

namespace ImuDataCommunication
{

class ImuMonitor : virtual public ::IceProxy::Ice::Object
{
public:

    void updateImuData(const ::ImuDataCommunication::OpenMatImuData& id)
    {
        updateImuData(id, 0);
    }
    void updateImuData(const ::ImuDataCommunication::OpenMatImuData& id, const ::Ice::Context& __ctx)
    {
        updateImuData(id, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_updateImuData(const ::ImuDataCommunication::OpenMatImuData& id, const ::IceInternal::Function<void ()>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_updateImuData(id, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(response, exception, sent));
    }
    ::Ice::AsyncResultPtr
    begin_updateImuData(const ::ImuDataCommunication::OpenMatImuData& id, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_updateImuData(id, 0, ::Ice::newCallback(completed, sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_updateImuData(const ::ImuDataCommunication::OpenMatImuData& id, const ::Ice::Context& ctx, const ::IceInternal::Function<void ()>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_updateImuData(id, &ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(response, exception, sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_updateImuData(const ::ImuDataCommunication::OpenMatImuData& id, const ::Ice::Context& ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_updateImuData(id, &ctx, ::Ice::newCallback(completed, sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_updateImuData(const ::ImuDataCommunication::OpenMatImuData& id)
    {
        return begin_updateImuData(id, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_updateImuData(const ::ImuDataCommunication::OpenMatImuData& id, const ::Ice::Context& __ctx)
    {
        return begin_updateImuData(id, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_updateImuData(const ::ImuDataCommunication::OpenMatImuData& id, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_updateImuData(id, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_updateImuData(const ::ImuDataCommunication::OpenMatImuData& id, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_updateImuData(id, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_updateImuData(const ::ImuDataCommunication::OpenMatImuData& id, const ::ImuDataCommunication::Callback_ImuMonitor_updateImuDataPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_updateImuData(id, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_updateImuData(const ::ImuDataCommunication::OpenMatImuData& id, const ::Ice::Context& __ctx, const ::ImuDataCommunication::Callback_ImuMonitor_updateImuDataPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_updateImuData(id, &__ctx, __del, __cookie);
    }

    void end_updateImuData(const ::Ice::AsyncResultPtr&);
    
private:

    void updateImuData(const ::ImuDataCommunication::OpenMatImuData&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_updateImuData(const ::ImuDataCommunication::OpenMatImuData&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<ImuMonitor> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<ImuMonitor*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<ImuMonitor> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<ImuMonitor*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<ImuMonitor> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<ImuMonitor*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<ImuMonitor> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<ImuMonitor*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<ImuMonitor> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<ImuMonitor*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<ImuMonitor> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<ImuMonitor*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<ImuMonitor> ice_secure(bool __secure) const
    {
        return dynamic_cast<ImuMonitor*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<ImuMonitor> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<ImuMonitor*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<ImuMonitor> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<ImuMonitor*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<ImuMonitor> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<ImuMonitor*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<ImuMonitor> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<ImuMonitor*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<ImuMonitor> ice_twoway() const
    {
        return dynamic_cast<ImuMonitor*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<ImuMonitor> ice_oneway() const
    {
        return dynamic_cast<ImuMonitor*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<ImuMonitor> ice_batchOneway() const
    {
        return dynamic_cast<ImuMonitor*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<ImuMonitor> ice_datagram() const
    {
        return dynamic_cast<ImuMonitor*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<ImuMonitor> ice_batchDatagram() const
    {
        return dynamic_cast<ImuMonitor*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<ImuMonitor> ice_compress(bool __compress) const
    {
        return dynamic_cast<ImuMonitor*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<ImuMonitor> ice_timeout(int __timeout) const
    {
        return dynamic_cast<ImuMonitor*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<ImuMonitor> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<ImuMonitor*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<ImuMonitor> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<ImuMonitor*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

class RawImuMonitor : virtual public ::IceProxy::Ice::Object
{
public:

    void updateImuData(const ::ImuDataCommunication::RawImuData& id)
    {
        updateImuData(id, 0);
    }
    void updateImuData(const ::ImuDataCommunication::RawImuData& id, const ::Ice::Context& __ctx)
    {
        updateImuData(id, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_updateImuData(const ::ImuDataCommunication::RawImuData& id, const ::IceInternal::Function<void ()>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_updateImuData(id, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(response, exception, sent));
    }
    ::Ice::AsyncResultPtr
    begin_updateImuData(const ::ImuDataCommunication::RawImuData& id, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_updateImuData(id, 0, ::Ice::newCallback(completed, sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_updateImuData(const ::ImuDataCommunication::RawImuData& id, const ::Ice::Context& ctx, const ::IceInternal::Function<void ()>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_updateImuData(id, &ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(response, exception, sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_updateImuData(const ::ImuDataCommunication::RawImuData& id, const ::Ice::Context& ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_updateImuData(id, &ctx, ::Ice::newCallback(completed, sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_updateImuData(const ::ImuDataCommunication::RawImuData& id)
    {
        return begin_updateImuData(id, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_updateImuData(const ::ImuDataCommunication::RawImuData& id, const ::Ice::Context& __ctx)
    {
        return begin_updateImuData(id, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_updateImuData(const ::ImuDataCommunication::RawImuData& id, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_updateImuData(id, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_updateImuData(const ::ImuDataCommunication::RawImuData& id, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_updateImuData(id, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_updateImuData(const ::ImuDataCommunication::RawImuData& id, const ::ImuDataCommunication::Callback_RawImuMonitor_updateImuDataPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_updateImuData(id, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_updateImuData(const ::ImuDataCommunication::RawImuData& id, const ::Ice::Context& __ctx, const ::ImuDataCommunication::Callback_RawImuMonitor_updateImuDataPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_updateImuData(id, &__ctx, __del, __cookie);
    }

    void end_updateImuData(const ::Ice::AsyncResultPtr&);
    
private:

    void updateImuData(const ::ImuDataCommunication::RawImuData&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_updateImuData(const ::ImuDataCommunication::RawImuData&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<RawImuMonitor> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<RawImuMonitor*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<RawImuMonitor> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<RawImuMonitor*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<RawImuMonitor> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<RawImuMonitor*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<RawImuMonitor> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<RawImuMonitor*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<RawImuMonitor> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<RawImuMonitor*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<RawImuMonitor> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<RawImuMonitor*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<RawImuMonitor> ice_secure(bool __secure) const
    {
        return dynamic_cast<RawImuMonitor*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<RawImuMonitor> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<RawImuMonitor*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<RawImuMonitor> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<RawImuMonitor*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<RawImuMonitor> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<RawImuMonitor*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<RawImuMonitor> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<RawImuMonitor*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<RawImuMonitor> ice_twoway() const
    {
        return dynamic_cast<RawImuMonitor*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<RawImuMonitor> ice_oneway() const
    {
        return dynamic_cast<RawImuMonitor*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<RawImuMonitor> ice_batchOneway() const
    {
        return dynamic_cast<RawImuMonitor*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<RawImuMonitor> ice_datagram() const
    {
        return dynamic_cast<RawImuMonitor*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<RawImuMonitor> ice_batchDatagram() const
    {
        return dynamic_cast<RawImuMonitor*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<RawImuMonitor> ice_compress(bool __compress) const
    {
        return dynamic_cast<RawImuMonitor*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<RawImuMonitor> ice_timeout(int __timeout) const
    {
        return dynamic_cast<RawImuMonitor*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<RawImuMonitor> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<RawImuMonitor*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<RawImuMonitor> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<RawImuMonitor*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace ImuDataCommunication
{

class ImuMonitor : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual void updateImuData(const ::ImuDataCommunication::OpenMatImuData&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

class RawImuMonitor : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual void updateImuData(const ::ImuDataCommunication::RawImuData&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace ImuDataCommunication
{

class ImuMonitor : virtual public ::IceDelegate::ImuDataCommunication::ImuMonitor,
                   virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual void updateImuData(const ::ImuDataCommunication::OpenMatImuData&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

class RawImuMonitor : virtual public ::IceDelegate::ImuDataCommunication::RawImuMonitor,
                      virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual void updateImuData(const ::ImuDataCommunication::RawImuData&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace ImuDataCommunication
{

class ImuMonitor : virtual public ::IceDelegate::ImuDataCommunication::ImuMonitor,
                   virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual void updateImuData(const ::ImuDataCommunication::OpenMatImuData&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

class RawImuMonitor : virtual public ::IceDelegate::ImuDataCommunication::RawImuMonitor,
                      virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual void updateImuData(const ::ImuDataCommunication::RawImuData&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace ImuDataCommunication
{

class ImuMonitor : virtual public ::Ice::Object
{
public:

    typedef ImuMonitorPrx ProxyType;
    typedef ImuMonitorPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void updateImuData(const ::ImuDataCommunication::OpenMatImuData&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___updateImuData(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const ImuMonitor& l, const ImuMonitor& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const ImuMonitor& l, const ImuMonitor& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

class RawImuMonitor : virtual public ::Ice::Object
{
public:

    typedef RawImuMonitorPrx ProxyType;
    typedef RawImuMonitorPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void updateImuData(const ::ImuDataCommunication::RawImuData&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___updateImuData(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const RawImuMonitor& l, const RawImuMonitor& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const RawImuMonitor& l, const RawImuMonitor& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace ImuDataCommunication
{

template<class T>
class CallbackNC_ImuMonitor_updateImuData : public Callback_ImuMonitor_updateImuData_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_ImuMonitor_updateImuData(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_ImuMonitor_updateImuDataPtr
newCallback_ImuMonitor_updateImuData(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ImuMonitor_updateImuData<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_ImuMonitor_updateImuDataPtr
newCallback_ImuMonitor_updateImuData(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ImuMonitor_updateImuData<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_ImuMonitor_updateImuDataPtr
newCallback_ImuMonitor_updateImuData(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ImuMonitor_updateImuData<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_ImuMonitor_updateImuDataPtr
newCallback_ImuMonitor_updateImuData(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ImuMonitor_updateImuData<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_ImuMonitor_updateImuData : public Callback_ImuMonitor_updateImuData_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_ImuMonitor_updateImuData(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_ImuMonitor_updateImuDataPtr
newCallback_ImuMonitor_updateImuData(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ImuMonitor_updateImuData<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_ImuMonitor_updateImuDataPtr
newCallback_ImuMonitor_updateImuData(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ImuMonitor_updateImuData<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_ImuMonitor_updateImuDataPtr
newCallback_ImuMonitor_updateImuData(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ImuMonitor_updateImuData<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_ImuMonitor_updateImuDataPtr
newCallback_ImuMonitor_updateImuData(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ImuMonitor_updateImuData<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_RawImuMonitor_updateImuData : public Callback_RawImuMonitor_updateImuData_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_RawImuMonitor_updateImuData(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_RawImuMonitor_updateImuDataPtr
newCallback_RawImuMonitor_updateImuData(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_RawImuMonitor_updateImuData<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_RawImuMonitor_updateImuDataPtr
newCallback_RawImuMonitor_updateImuData(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_RawImuMonitor_updateImuData<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_RawImuMonitor_updateImuDataPtr
newCallback_RawImuMonitor_updateImuData(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_RawImuMonitor_updateImuData<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_RawImuMonitor_updateImuDataPtr
newCallback_RawImuMonitor_updateImuData(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_RawImuMonitor_updateImuData<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_RawImuMonitor_updateImuData : public Callback_RawImuMonitor_updateImuData_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_RawImuMonitor_updateImuData(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_RawImuMonitor_updateImuDataPtr
newCallback_RawImuMonitor_updateImuData(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_RawImuMonitor_updateImuData<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_RawImuMonitor_updateImuDataPtr
newCallback_RawImuMonitor_updateImuData(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_RawImuMonitor_updateImuData<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_RawImuMonitor_updateImuDataPtr
newCallback_RawImuMonitor_updateImuData(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_RawImuMonitor_updateImuData<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_RawImuMonitor_updateImuDataPtr
newCallback_RawImuMonitor_updateImuData(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_RawImuMonitor_updateImuData<T, CT>(instance, 0, excb, sentcb);
}

}

#endif
